export const movieConstants = {
  LIST_REQUEST: 'MOVIES_LIST_REQUEST',
  LIST_SUCCESS: 'MOVIES_LIST_SUCCESS',
	LIST_FAILURE: 'MOVIES_LIST_FAILURE',

	SORT_UPDATE: 'MOVIES_SORT_UPDATE',
	USER_FILTER_UPDATE: 'MOVIES_FILTERS_UPDATE',

	POST_REQUEST: 'MOVIES_POST_REQUEST',
  POST_SUCCESS: 'MOVIES_POST_SUCCESS',
	POST_FAILURE: 'MOVIES_POST_FAILURE',
	
	LIKE_REQUEST: 'MOVIES_LIKE_REQUEST',
  LIKE_SUCCESS: 'MOVIES_LIKE_SUCCESS',
	LIKE_FAILURE: 'MOVIES_LIKE_FAILURE',
	
	HATE_REQUEST: 'MOVIES_HATE_REQUEST',
  HATE_SUCCESS: 'MOVIES_HATE_SUCCESS',
  HATE_FAILURE: 'MOVIES_HATE_FAILURE',

  REVOKE_OPINION_REQUEST: 'MOVIES_REVOKE_OPINION_REQUEST',
  REVOKE_OPINION_SUCCESS: 'MOVIES_REVOKE_OPINION_SUCCESS',
  REVOKE_OPINION_FAILURE: 'MOVIES_REVOKE_OPINION_FAILURE'
};
