USE [master]
GO

/****** Object:  Database [MovieRama]    Script Date: 9/16/2018 4:12:07 PM ******/
CREATE DATABASE [MovieRama]
 CONTAINMENT = NONE
GO

ALTER DATABASE [MovieRama] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MovieRama].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MovieRama] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MovieRama] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MovieRama] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MovieRama] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MovieRama] SET ARITHABORT OFF 
GO

ALTER DATABASE [MovieRama] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MovieRama] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MovieRama] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MovieRama] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MovieRama] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MovieRama] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MovieRama] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MovieRama] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MovieRama] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MovieRama] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MovieRama] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MovieRama] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MovieRama] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MovieRama] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [MovieRama] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MovieRama] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MovieRama] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MovieRama] SET RECOVERY FULL 
GO

ALTER DATABASE [MovieRama] SET  MULTI_USER 
GO

ALTER DATABASE [MovieRama] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MovieRama] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MovieRama] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MovieRama] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MovieRama] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MovieRama] SET QUERY_STORE = OFF
GO

USE [MovieRama]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [MovieRama] SET  READ_WRITE 
GO


